spring:
  freemarker:
    cache: false
  security:
    oauth2:
      client:
        registration:
          ghe:
            client-name: ghe
            client-id: 582219d0d82ba0837912
            client-secret: a61f5fa013b625d2cdecee49ca53f5476cee742d
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          ghe:
            authorization-uri: https://code.cargurus.com/login/oauth/authorize
            token-uri: https://code.cargurus.com/login/oauth/access_token
            user-info-uri: https://code.cargurus.com/api/v3/user
            user-name-attribute: login

percolator:
  clusters:
    - name: site-cars
      apps:
        - name: devbox-na-me slice
          host: devbox-na-me
          port: 9090
        - name: devbox-na-me stage
          host: devbox-na-me
          port: 9100
    - name: site-tools
      apps:
        - name: devbox-na-me slice
          host: devbox-na-me
          port: 9150
        - name: devbox-na-me stage
          host: devbox-na-me
          port: 9151
